AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Tracker Backend

#Globals:
#  Function:
#    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary'

Parameters:
  AppId:
    Type: String

Resources:

  LocationPersist:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/location-persist.locationPersistHandler
      Runtime: nodejs14.x
      Description: Locations events in Queue persist in Database
      MemorySize: 128
      Timeout: 300
      Policies:
        - SQSPollerPolicy:
            QueueName:
              !GetAtt TrackerIn.QueueName
        - DynamoDBCrudPolicy:
            TableName: !Ref LocationLogTable
      Environment:
        Variables:
          LOCATION_LOG_TABLE: !Ref LocationLogTable
      Events:
        TrackerIn:
          Type: SQS
          Properties:
            Queue: !GetAtt TrackerIn.Arn

  TrackerIn:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: alias/aws/sqs
      VisibilityTimeout: 2000

  LocationLogTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
